name: Build and Push Docker Image

on:
  workflow_dispatch:
  schedule:    
    - cron: '0 0 1 * *' # Runs at 00:00 on the 1st of every month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.POLY_PACKAGE_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/polymorphic-group/flutter:latest .

      - name: Extract Flutter version
        run: |
          FLUTTER_VERSION=$(docker run --rm ghcr.io/polymorphic-group/flutter:latest flutter --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "Flutter version: $FLUTTER_VERSION"
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV

      - name: Tag Docker image with version
        run: docker tag ghcr.io/polymorphic-group/flutter:latest ghcr.io/polymorphic-group/flutter:${{ env.FLUTTER_VERSION }}

      - name: Push Docker images to GitHub Container Registry
        run: |
          docker push ghcr.io/polymorphic-group/flutter:latest
          docker push ghcr.io/polymorphic-group/flutter:${{ env.FLUTTER_VERSION }}
