name: Build and Push Docker Image

on:
  workflow_dispatch:
  schedule:    
    - cron: '0 0 1 * *' # Runs at 00:00 on the 1st of every month

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      flutter_version: ${{ steps.extract_version.outputs.flutter_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.POLY_PACKAGE_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/polymorphic-group/flutter:latest .

      - name: Extract Flutter version
        id: extract_version
        run: |
          FLUTTER_VERSION=$(docker run --rm ghcr.io/polymorphic-group/flutter:latest flutter --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          echo "Flutter version: $FLUTTER_VERSION"
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV
          echo "flutter_version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT

      - name: Tag Docker image with version
        run: docker tag ghcr.io/polymorphic-group/flutter:latest ghcr.io/polymorphic-group/flutter:${{ env.FLUTTER_VERSION }}

      - name: Push Docker images to GitHub Container Registry
        run: |
          docker push ghcr.io/polymorphic-group/flutter:latest
          docker push ghcr.io/polymorphic-group/flutter:${{ env.FLUTTER_VERSION }}

  build-with-deps:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.POLY_PACKAGE_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image with dependencies
        run: docker build -f Dockerfile.with-deps -t ghcr.io/polymorphic-group/flutter:with-deps .

      - name: Tag Docker image with Flutter version
        run: docker tag ghcr.io/polymorphic-group/flutter:with-deps ghcr.io/polymorphic-group/flutter:with-deps-${{ needs.build.outputs.flutter_version }}

      - name: Push Docker images with dependencies
        run: |
          docker push ghcr.io/polymorphic-group/flutter:with-deps
          docker push ghcr.io/polymorphic-group/flutter:with-deps-${{ needs.build.outputs.flutter_version }}
